"""
Shared TitanBI form fields for O'Donoghues Bar.

Terminal IDs and department IDs are static — only date fields change per request.
Captured from live browser session 2026-07-21.
"""

BASE_URL = "https://titanbi.net"
CRITERIA_URL = f"{BASE_URL}/Analysis/AnalyzeParameters/CriteriaPerformanceByHour"

STATIC_PAIRS = [
    ("Model.SelectedPeriodMode", "0"),
    ("Model.SelectedSortMode", "1"),
    ("Model.DrillDown", "true"),
    ("Model.DrillDown", "false"),
    ("Model.SelectedPeriodGroupMode", ""),
    ("Model.SelectedPeriodIntervalMode", "0"),
    ("Model.FirstHour", "0"),
    ("Model.LastHour", "23"),
    # Terminals: BAR T1=2146, BAR PAD T2=2147, UPSTAIR T3=2148, BAR T4=2208
    ("Model.SelectableCheckListPosUnit.SelectableCheckListItems[0].Id", "2146"),
    ("Model.SelectableCheckListPosUnit.SelectableCheckListItems[0].Checked", "true"),
    ("Model.SelectableCheckListPosUnit.SelectableCheckListItems[0].Checked", "false"),
    ("Model.SelectableCheckListPosUnit.SelectableCheckListItems[1].Id", "2147"),
    ("Model.SelectableCheckListPosUnit.SelectableCheckListItems[1].Checked", "true"),
    ("Model.SelectableCheckListPosUnit.SelectableCheckListItems[1].Checked", "false"),
    ("Model.SelectableCheckListPosUnit.SelectableCheckListItems[2].Id", "2148"),
    ("Model.SelectableCheckListPosUnit.SelectableCheckListItems[2].Checked", "true"),
    ("Model.SelectableCheckListPosUnit.SelectableCheckListItems[2].Checked", "false"),
    ("Model.SelectableCheckListPosUnit.SelectableCheckListItems[3].Id", "2208"),
    ("Model.SelectableCheckListPosUnit.SelectableCheckListItems[3].Checked", "true"),
    ("Model.SelectableCheckListPosUnit.SelectableCheckListItems[3].Checked", "false"),
    # Department groups — all checked
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[0].Favorite", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[0].Id", "839"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[0].SelectableCheckListItems[0].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[0].SelectableCheckListItems[0].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[0].SelectableCheckListItems[0].Id", "9695"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[1].Favorite", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[1].Id", "832"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[1].SelectableCheckListItems[0].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[1].SelectableCheckListItems[0].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[1].SelectableCheckListItems[0].Id", "6608"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].Favorite", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].Id", "830"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[0].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[0].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[0].Id", "6156"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[1].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[1].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[1].Id", "9693"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[2].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[2].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[2].Id", "6159"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[3].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[3].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[3].Id", "6171"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[4].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[4].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[4].Id", "6155"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[5].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[5].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[5].Id", "6172"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[6].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[6].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[6].Id", "6161"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[7].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[7].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[7].Id", "13368"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[8].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[8].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[8].Id", "6158"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[9].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[9].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[9].Id", "6174"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[10].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[10].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[10].Id", "6157"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[11].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[11].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[2].SelectableCheckListItems[11].Id", "6160"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].Favorite", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].Id", "831"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[0].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[0].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[0].Id", "13369"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[1].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[1].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[1].Id", "6162"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[2].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[2].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[2].Id", "6169"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[3].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[3].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[3].Id", "6167"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[4].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[4].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[4].Id", "6173"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[5].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[5].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[5].Id", "6163"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[6].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[6].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[6].Id", "6165"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[7].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[7].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[7].Id", "6175"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[8].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[8].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[8].Id", "9694"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[9].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[9].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[9].Id", "13370"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[10].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[10].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[10].Id", "13374"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[11].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[11].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[11].Id", "13372"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[12].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[12].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[12].Id", "13373"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[13].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[13].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[13].Id", "13371"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[14].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[14].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[14].Id", "6166"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[15].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[15].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[15].Id", "6164"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[16].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[16].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[3].SelectableCheckListItems[16].Id", "9697"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[4].Favorite", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[4].Id", "838"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[4].SelectableCheckListItems[0].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[4].SelectableCheckListItems[0].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[4].SelectableCheckListItems[0].Id", "9696"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[5].Favorite", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[5].Id", "837"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[5].SelectableCheckListItems[0].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[5].SelectableCheckListItems[0].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[5].SelectableCheckListItems[0].Id", "10782"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[5].SelectableCheckListItems[1].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[5].SelectableCheckListItems[1].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[5].SelectableCheckListItems[1].Id", "10046"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[6].Favorite", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[6].Id", "835"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[6].SelectableCheckListItems[0].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[6].SelectableCheckListItems[0].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[6].SelectableCheckListItems[0].Id", "6168"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[7].Favorite", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[7].Id", "833"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[7].SelectableCheckListItems[0].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[7].SelectableCheckListItems[0].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[7].SelectableCheckListItems[0].Id", "6609"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[8].Favorite", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[8].Id", "2501"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[8].SelectableCheckListItems[0].Checked", "true"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[8].SelectableCheckListItems[0].Checked", "false"),
    ("Model.HierarchicalSelectableCheckListMainGroup.HierarchicalSelectableCheckListItems[8].SelectableCheckListItems[0].Id", "6170"),
    # Days of week — all included
    ("Model.ShowMonday", "true"),    ("Model.ShowMonday", "false"),
    ("Model.ShowTuesday", "true"),   ("Model.ShowTuesday", "false"),
    ("Model.ShowWednesday", "true"), ("Model.ShowWednesday", "false"),
    ("Model.ShowThursday", "true"),  ("Model.ShowThursday", "false"),
    ("Model.ShowFriday", "true"),    ("Model.ShowFriday", "false"),
    ("Model.ShowSaturday", "true"),  ("Model.ShowSaturday", "false"),
    ("Model.ShowSunday", "true"),    ("Model.ShowSunday", "false"),
]
